name: Python CI
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'  # Only trigger if files in the infra directory change
  pull_request:
    branches:
      - '**'           # All branches
    paths:
      - 'src/**'  # Only trigger if files in the infra directory change


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r src/requirements.txt pytest
      - run: pytest tests/

  cloud-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - run: |
          gcloud functions deploy test-fn${{ github.ref_name }} \
            --region=europe-west2 \
            --runtime=python312 \
            --entry-point=main_http \
            --source=./src \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --trigger-http
            --labels env=branch,date=$(date +%Y-%m-%d) \
