name: CI
on:
  push:
    branches:
      - '**'           # All branches
    paths:
      - 'src/**'  # Only trigger if files in the infra directory change
  pull_request:
    branches:
      - '**'           # All branches
    paths:
      - 'src/**'  # Only trigger if files in the infra directory change


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r src/requirements.txt pytest
      - run: pytest tests/