name: Python CI
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'  # Only trigger if files in the infra directory change
  pull_request:
    branches:
      - '**'           # All branches
    paths:
      - 'src/**'  # Only trigger if files in the infra directory change


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r src/requirements.txt pytest
      - run: pytest tests/

  cloud-deploy:
    environment: uat
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_SA_KEY }}      
      - id: set-func-name
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "branch=main" >> $GITHUB_OUTPUT
            echo "function_name=my-function" >> $GITHUB_OUTPUT
          else
            echo "branch=branch" >> $GITHUB_OUTPUT
            echo "function_name=test-function-$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
      - run: |
          gcloud functions deploy ${{ steps.set-func-name.outputs.function_name }} \
            --region=europe-west2 \
            --runtime=python312 \
            --entry-point=main_http \
            --source=./src \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --trigger-http \
            --no-allow-unauthenticated \
            --quiet
