name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'  # Only trigger if files in the infra directory change
  pull_request:
    branches:
      - '**'
    paths:
      - 'infra/**'  # Only trigger if files in the infra directory change

jobs:
  terraform:
    environment: uat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2  # Specify your Terraform version

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          #workload_identity_provider: 'projects/${{secrets.GCP_PROJECT_ID}}/locations/global/workloadIdentityPools/github-pool/providers/github-provider-3'
          #service_account: 'terraform-pipeline@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com'

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.GCP_PROJECT }}-terraform-state"
        working-directory: ./infra  # Pointing to the infra directory

      - name: Terraform Plan
        run: terraform plan -backend-config="bucket=${{ secrets.GCP_PROJECT }}-terraform-state"
        working-directory: ./infra  # Pointing to the infra directory